### PR TITLE
Log Links CloudWatch FluentD

### PR DESCRIPTION
**Pull request by Smartmind12**
Signed-off-by: Utsav Paul <91927689+Smartmind12@users.noreply.github.com>

## Type
 - [X] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [X] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 Change the default template defined so that Log Links work with CloudWatch FluentD Out Of the Box  

## Tracking Issue

fixes https://github.com/flyteorg/flyte/issues/2635

### CODE REVIEW

**Comment by samhita-alla** [comment]
@Smartmind12, thanks for creating the PR. But since the issue is assigned to a different person who created a PR already, I'm going to close this.

**Comment by Smartmind12** [comment]
@samhita-alla Was it not first PR submitted will be checked first kind of rule??

**Comment by Smartmind12** [comment]
& also the other PR has the wrong command being commited so kindly reopen this PR!

**Comment by samhita-alla** [comment]
@Smartmind12, it is. When there are two PRs, I'll have to merge the one that has been fixed by the assignee. Also, what's wrong in the other PR?

**Pull request closed without merging**
